### ISSUE TITLE
Weather Insight

### ISSUE THREAD

**Issue by hkgian** [IBM-Bluemix/capital-weather#10]
Hi, 
I cannot find the weather Insight service on the catalog, can you please update the repo?

**Comment by jakepeyser** [comment]
@hkgian link has been updated, you can [find the service](https://console.ng.bluemix.net/catalog/services/weather-company-data/) here for reference

**Comment by hkgian** [comment]
Thanks a lot Jake!
Can you also update the cf command?

**Comment by jakepeyser** [comment]
I'd rather someone with access to the live demo update that, along with the manifest file, as I'm not sure if a CI pipeline is still in place. @l2fprod ahoy! Could you do this when you have some time?
